### ISSUE TITLE
XRP Never Arrived

### ISSUE THREAD

**Issue by ckru8789** [sologenic/sologenic-expo-wallet#204]
I sent around 2,153 XRP & it never arrived. Switching nodes isn’t working, and switching it still won’t help receive the XRP. The transaction was recorded on my other ledger as having been sent out. Did my wallet “eat” the XRP or is this site a scam & I’m out of luck?
Either way, extremely disappointed.

**Comment by ayoobshab** [comment]
Waht can I do for this problem?

**Comment by ayoobshab** [comment]
Please help me
