### ISSUE TITLE
Still havent gotten xrp in wallet

### ISSUE THREAD

**Issue by Scottswan89** [sologenic/sologenic-expo-wallet#227]
Hi, I sent my xrp from coinbase quite a bit ago, and it's still not in my wallet....how long should it take? For the sol snapshot do I need to do anything?

**Comment by Silverhawk0251** [comment]
Been over 12 hours for me. 3 transfers from Coinbase. First small one went in seconds. Next two are stuck

**Comment by Scottswan89** [comment]
That's so weird, I sent one big one an hour ago. Ugh it could really take that long? I'm going to miss the damn drop which is the only reason I transferred to here.

**Comment by Scottswan89** [comment]
When you say stuck, you mean it's just not moving and it's been over 12 hours? Thanks for letting me know too.

**Comment by Silverhawk0251** [comment]
Says pending at Coinbase. They tried to "manually" move it and didn't work. Been in pending status now for 16 hours. I can't cancel it on Coinbase end and it doesn't show on solo DEX end.

**Comment by Silverhawk0251** [comment]
From Coinbase: 
When customers attempt to withdraw large amounts of this asset all at once, it can lead to longer queues for those withdrawals to process.

**Comment by Silverhawk0251** [comment]
Made it now. Nearly 18 hours
