### ISSUE TITLE
Airdrop vanished 

### ISSUE THREAD

**Issue by Fulzal** [sologenic/sologenic-expo-wallet#347]
I opened my wallet and seen the airdrop had taken place.  When I went back to it, it had vanished. Can someone please help.

**Comment by matt-mulraney** [comment]
I had the same issue. Air drop appeared with $0 balance and then disappeared

**Comment by Zaibraja83** [comment]
Hi have the same issue. All of my purchased solo, XRP and airdropped solo ha e disappeared. Also the statust of XRP and Solo account changed to "not activated". This is worrying as this was about 95% of my investment. 
Can someone please help or know how to get in touch with admin? 
Thanks

**Comment by Fulzal** [comment]
yes finally received airdrop.
