### ISSUE TITLE
No airdrop in my SOLODEX WALLET

### ISSUE THREAD

**Issue by Confusedaswell** [sologenic/sologenic-expo-wallet#381]
Still haven't received the solo token airdrop for xrp holders.

**Comment by aarondougherty710** [comment]
I haven’t received mine either! I went through all of the steps, I’ve been hoping XRP for years.

**Comment by mcreedd** [comment]
Any luck I haven't either ?

**Comment by Boykedhonre** [comment]
Still haven't received mine solo token airdrop for xrp holders.

**Comment by Riskit4biscuit** [comment]
I'm still waiting as well.

**Comment by Confusedaswell** [comment]
Received the solo airdrop.  THANK YOU.

**Comment by Boykedhonre** [comment]
Getting a little bit tired of writing messages without any reply back or any results. Just waiting and waiting till I get my solo tokens. Getting dissapointed now.
