### ISSUE TITLE
Tag setting error

### ISSUE THREAD

**Issue by TKMS9** [sologenic/sologenic-expo-wallet#464]
Tag cannot be set on the app ("processing" never end).
Tag is required when I send XRP or SOLO from Gate.io.
So I cannot receive/send anything with the app.
![Screenshot_20220207_085101_com sologenicwallet](https://user-images.githubusercontent.com/97742023/152706999-7d9a885f-b533-4949-99c1-9fb90f0e9570.jpg)

**Comment by wesrt36** [comment]
I would think since it's your wallet that if you just put a random destination tag it wouldn't matter, just my opinion
