### ISSUE TITLE
APP CHANGED DESTINATION TAG AND SENT FUNDS TO SOMEONE ELSE 

### ISSUE THREAD

**Issue by G2barbour** [sologenic/sologenic-expo-wallet#48]
I tried to send Casinocoin to Bitrue. 

I used the correct wallet address and memo.

I confirm that I input the correct memo, as autofill still recalls the correct destination. 

However, the xrpl shows that the app used an entirely different destination tag, not even remotely close to mine or even the same number of digits.

**Comment by Breyday** [comment]
Have you received any assistance with your issue(s) of missing and/or vanishing XRP or other cryptocurrency? 
I'm having the same issue and it appears that others are also having complaints about the same or very similar issues.

**Comment by sologenic** [comment]
This issue has been fixed on the latest version. 2.0.1

Please open a support ticket with Bitrue to recover the funds sent to wrong DT. They will deposit it to your account.

**Comment by G2barbour** [comment]
Yes I did that. They say it will take 10 days. Instead of doubling my money it is halved thanks to this app.
