### ISSUE TITLE
Core airdrop

### ISSUE THREAD

**Issue by Garrett-Solo** [sologenic/sologenic-expo-wallet#515]
Hi Solo

Please can you let me know when February core airdrop is happening, its now the 28th.

Many thanks

Garrett

**Comment by TKMS9** [comment]
I have the same question. It's March already.

**Comment by Garrett-Solo** [comment]
Hope you've created the trust line for Core... Sologenic might be a bit late but they do follow through and do what they say they going to do. I received my Solo airdrop... I believe in this project and so Im invested for the long term.

**Comment by Boykedhonre** [comment]
I have the same question.

**Comment by Boykedhonre** [comment]
I have my solo tokens in solo dex and still not yet received my core airdrops

**Comment by Garrett-Solo** [comment]
Make sure you have opened the trust line for core. Open the Solo dex, at the top you will find a link for instuctions. Read it all. I'm still waiting and I've created a trust line....

**Comment by Garrett-Solo** [comment]
I've received my Core....

**Comment by Boykedhonre** [comment]
I have created a trust line for core long time ago and its active.

**Comment by Garrett-Solo** [comment]
Sologenic will do the airdrop...Dont worry...

**Comment by TKMS9** [comment]
I see...
I didn't receive any SOLO and CORE.
But will wait a bit more...
I have the trust line of course.

**Comment by TKMS9** [comment]
![Screenshot_20220305_155104](https://user-images.githubusercontent.com/97742023/156905913-4d375d7e-f265-4ac7-825f-ff27683be1a6.jpg)
I still didn't receive any tokens.

**Comment by Garrett-Solo** [comment]
Did you have this balance when the snap shot was taken in December? I dont know why they wouldnt airdrop you... I wish I could help you more...

**Comment by TKMS9** [comment]
Thanks Gorrett,
Oh, let me clarify that I had to have the trust line in "Dec" to receive the "Feb" Airdrop? 
If so, I cannot receive the airdrop because I created the trustline in early Feb. It's a kind of my faults...

If I understand correctly, I can receive airdrops after the March or Feb?
![Screenshot_20220307_143709](https://user-images.githubusercontent.com/97742023/156974752-2a06f53c-59f2-49f6-89b9-f91eca4b679a.jpg)

**Comment by Garrett-Solo** [comment]
Yes.. You will receive the rest of this years airdrops. Good luck!

**Comment by TKMS9** [comment]
Great! Thanks a lot!

**Comment by Garrett-Solo** [comment]
Further thought to our conversation.... If you were holding your Solo tokens while the snap shots were taken in December you should still receive your airdrops once you  created a trust line. In my opinion holding Solo when the snap shots are taken is the important thing.  Ask Sologenic to honour
